# Generated by Django 3.2.6 on 2021-08-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='botSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_token', models.CharField(max_length=200, verbose_name='Токен бота')),
                ('tg_chat', models.CharField(max_length=200, verbose_name='id Телеграм чата или человека')),
            ],
        ),
    ]
