# Generated by Django 3.2.6 on 2021-08-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SrevicePrices',
            new_name='ServicePrices',
        ),
        migrations.AlterModelOptions(
            name='serviceprices',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='subscribeprices',
            options={'verbose_name': 'Подписку', 'verbose_name_plural': 'Подписки'},
        ),
    ]
